# Generated by Django 5.0.4 on 2024-04-15 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Qism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UsersBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user_id', models.PositiveBigIntegerField()),
                ('created', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mavzu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savol', models.TextField()),
                ('javob', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('savol_id', models.PositiveIntegerField(default=92674, unique=True)),
                ('bolim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolim', to='api.bolim')),
                ('qism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qism', to='api.qism')),
            ],
        ),
    ]
