# Generated by Django 5.0.4 on 2024-04-16 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mavzu',
            name='savol_id',
        ),
        migrations.AlterField(
            model_name='mavzu',
            name='bolim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mavzular', to='api.bolim'),
        ),
        migrations.AlterField(
            model_name='mavzu',
            name='qism',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mavzular', to='api.qism'),
        ),
    ]
